### PR TITLE
Update Run in Explorer button icon

### PR DESCRIPTION
**Pull request by jglovier**
This PR updates the Run in Explorer button icon to match the Run in Explorer button in Studio.

| Before | After |
|---|---|
|image|image|

### CODE REVIEW

**Comment by jglovier** [comment]
🤔 ...for some reason it appears the new icon is pushing the text down. In the before, the icon, line number, and text row all appear aligned-middle. In the after image, the text row appears aligned-baseline. I'd like them to be aligned-middle, but not sure how to adjust this.

**Comment by jgzuke** [comment]
@jglovier  https://github.com/apollographql/vscode-graphql/pull/32 should fix the icon pushing down the text (and the pushing to the right as well)

**Comment by jgzuke** [comment]
@cy mind doing a quick double check here?

**Comment by cy** [comment]
Screen Shot 2021-10-12 at 4 09 33 PM
The button overlaps the first character of `query` for me - is it just my resolution? Zooming in and out still has the same issue.

Screen Shot 2021-10-12 at 4 12 15 PM
Changing the default theme has the overlap too

**Comment by jgzuke** [comment]
@cy only added the negative margin when text was indented, does that seem like a decent solution?

**Review by cy — APPROVED** [review]
yeah. Looks good now!

**Comment by jglovier** [comment]
Is the triangle balanced a little low for anyone else, or is it just me?

image

(also not sure how it got filled in...if we want to be consistent with Studio it needs to just be the outline)

**Pull request merged**
