### PR TITLE
fix regex for ruby heredoc

### LINKED ISSUE #74: Issues with GraphQL heredoc in ruby files
Hello,

While working on Ruby on Rails project, I noticed that the highlighting in the spec files is somehow wrong when using heredocs for GraphQL. It seems that after the first GraphQL heredoc, everything goes in yellow, the formatting while writing and the autocomplete doesn't work. I'm attaching a screenshot.

Example:

```
# foo_spec.rb

require 'rails_helper'

module Graph
  module Mutations
    describe FooMutation do
      it 'flags foo' do
        foo = create :foo

        resolve <<~GRAPHQL, id: foo.id, flag: true
          mutation($id: ID!, $flag: Boolean!) {
            flagFoo(input: {id: $id, flag: $flag}) {
              foo {
                flagged
              }
            }
          }
        GRAPHQL

        response_data.should eq 'flagFoo' => {'foo' => {'flagged' => true}]}
      end

      it 'unflags foo' do
        foo = create :foo

        resolve <<~GRAPHQL, id: foo.id, flag: false
          mutation($id: ID!, $flag: Boolean!) {
            flagFoo(input: {id: $id, flag: $flag}) {
              foo {
                flagged
              }
            }
          }
        GRAPHQL

        response_data.should eq 'flagFoo' => {'foo' => {'flagged' => false}}
      end
    end
  end
end


```

</details>

<details>
<summary>Screenshot</summary>

Screenshot 2022-05-25 at 14 56 53

</details>

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-1307) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by jtgrenz**
Fixes https://github.com/apollographql/vscode-graphql/issues/74 

I ran into this issue where the syntax highlighting got all borked when ApolloGraphQL was installed but noticed that other extensions were working fine. For example: https://github.com/kumarharsh/graphql-for-vscode/blob/master/syntaxes/graphql.rb.json. This PR uses the same regex which seems to resolve the issue. 

First time contributing here, so let me know if theres anything else needed to merge this.

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-1416) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by jtgrenz** [comment]
Hey @jgzuke, I forgot about this PR since I'm apparently still running a forked version of the extension. Someone on my team pointed out they're still having this issue. Any chance I can get you or one of the other maintainers to give this a review when you get a chance?

**Comment by jgzuke** [comment]
Hi! I no longer work on this project, @cy maybe?

**Comment by jtgrenz** [comment]
@martijnwalraven are you a still a maintainer?

**Comment by alessbell** [comment]
Hi @jtgrenz 👋 Doing some maintenance and will be merging this imminently - thanks for your patience!

**Review by alessbell — APPROVED** [review]
Thanks @jtgrenz!

**Pull request merged**
